package cz.quantumleap.core.data.entity;

import cz.quantumleap.core.data.mapper.MapperUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.Validate;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.impl.DSL;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class EntityIdentifier<TABLE extends Table<? extends Record>> {

    private final TABLE table;
    private final String qualifier;

    public EntityIdentifier(TABLE table, String qualifier) {
        Validate.notNull(table);
        this.table = table;
        this.qualifier = qualifier;
    }

    public static <TABLE extends Table<? extends Record>> EntityIdentifier<TABLE> forTable(TABLE table) {
        return forTableWithQualifier(table, null);
    }

    public static <TABLE extends Table<? extends Record>> EntityIdentifier<TABLE> forTableWithQualifier(TABLE table, String qualifier) {
        return new EntityIdentifier<>(table, qualifier);
    }

    public TABLE getTable() {
        return table;
    }

    public String getQualifier() {
        return qualifier;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        EntityIdentifier<?> that = (EntityIdentifier<?>) o;
        // Generated table does not have fully qualified name even though the
        // Table object holds a schema name. So we will compare schema name and
        // unqualified table name separately.
        return Objects.equals(table.getSchema(), that.getTable().getSchema()) &&
                Objects.equals(table.getUnqualifiedName(), that.table.getUnqualifiedName()) &&
                Objects.equals(qualifier, that.qualifier);
    }

    @Override
    public int hashCode() {
        return Objects.hash(table.getSchema().getName(), table.getUnqualifiedName(), qualifier);
    }

    /**
     * Outputs this identifier as a string which can be parsed by parse method
     * to recreate the object.
     */
    @Override
    public String toString() {
        String value = MapperUtils.resolveDatabaseTableNameWithSchema(table);
        if (StringUtils.isNotBlank(qualifier)) {
            value += '#' + qualifier;
        }
        return value;
    }

    /**
     * Parse entity identifier from a string generated by the toString method
     * of this class, or by the jOOQ.Table.toString() method.
     */
    public static EntityIdentifier<?> parse(String text) {
        List<String> fragments = new ArrayList<>(3);
        int len = text.length();
        int fragmentStart = -1;
        boolean escaped = false;

        for (int i = 0; i < text.length(); i++) {
            char chr = text.charAt(i);
            if ((chr == '.' || chr == '#' || chr == '"') && !escaped && fragmentStart > -1) {
                fragments.add(text.substring(fragmentStart, i));
                fragmentStart = -1;
            } else if (chr != '.' && chr != '#' && chr != '"' && !escaped && fragmentStart == -1) {
                fragmentStart = i;
            } else if (chr == '\\' && !escaped) {
                escaped = true;
            } else if (escaped) {
                escaped = false;
            }
        }

        if (fragmentStart > -1 && fragmentStart < len) {
            fragments.add(text.substring(fragmentStart, len));
        }

        if (fragments.size() < 2 || fragments.size() > 3) {
            throw new IllegalArgumentException("Cannot parse " + text + " to EntityIdentifier!");
        }

        String schemaName = fragments.get(0);
        String tableName = fragments.get(1);
        String qualifier = fragments.size() > 2 ? fragments.get(2) : null;

        Name name = DSL.name(schemaName, tableName);
        Table<?> table = DSL.table(name);
        return EntityIdentifier.forTableWithQualifier(table, qualifier);
    }
}
